---
  haproxy:    # https://hub.docker.com/r/bringnow/haproxy-letsencrypt/
    image: bringnow/haproxy-letsencrypt:latest
    ports:
      - "80:80"
      - "443:443"
#    links:
#      - reaction
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/var/acme-webroot:/var/lib/haproxy/"
      - "~/shop/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"    # https://github.com/camptocamp/docker-haproxy-luasec
      #- "~/shop/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"    # https://github.com/camptocamp/docker-haproxy-luasec
    restart: always

